# Visit https://golangci-lint.run/ for usage documentation
# and information on other useful linters
version: "2"
issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  enable:
    - forcetypeassert
    - godot
    - misspell
    - staticcheck
    - govet

formatters:
  enable:
    - gofmt

